#!/usr/bin/env sh

# the scripting-addition must be loaded manually if
# you are running yabai on macOS Big Sur. Uncomment
# the following line to have the injection performed
# when the config is executed during startup.
#
# for this to work you must configure sudo such that
# it will be able to run the command without password
#
# see this wiki page for information:
#  - https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)
#
sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

# global settings
yabai -m config mouse_follows_focus          off
yabai -m config focus_follows_mouse          off
yabai -m config window_placement             second_child
yabai -m config window_topmost               off
yabai -m config window_shadow                on
yabai -m config window_opacity               off
yabai -m config window_opacity_duration      0.0
yabai -m config active_window_opacity        1.0
yabai -m config normal_window_opacity        0.90
yabai -m config window_border                off
yabai -m config window_border_width          6
yabai -m config active_window_border_color   0xff775759
yabai -m config normal_window_border_color   0xff555555
yabai -m config insert_feedback_color        0xffd75f5f
yabai -m config split_ratio                  0.50
yabai -m config auto_balance                 off
yabai -m config mouse_modifier               fn
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize
yabai -m config mouse_drop_action            swap

# general space settings
yabai -m config layout                       bsp
yabai -m config top_padding                  0
yabai -m config bottom_padding               0
yabai -m config left_padding                 0
yabai -m config right_padding                0
yabai -m config window_gap                   06

yabai -m rule --add app="^Free Download Manager$" manage=off
yabai -m rule --add app="^Zoom$" manage=off
#yabai -m rule --add app="^Todoist$" manage=off
yabai -m rule --add app="^Slack$" manage=off
#yabai -m rule --add app="^Spotify$" manage=off
yabai -m rule --add app="^System Preferences$" manage=off
yabai -m rule --add app="^The Unarchiver$" manage=off
yabai -m rule --add app="^NordVPN$" manage=off
yabai -m rule --add app="^Bitwarden$" manage=off
yabai -m rule --add app="^MiniDSP$" manage=off
yabai -m rule --add app="^Webex$" manage=off
yabai -m rule --add app="^Karabiner$" manage=off
yabai -m rule --add app="^KSP$" manage=off

# Snippet to disable wm for the mac internal screen
yabai -m query --spaces --display 3 |
  jq '.[] | select(."native-fullscreen" == 0).index' |
  xargs -I{} yabai -m space {} --layout float

read -r -d '' action <<- 'EOF'
  yabai -m query --spaces --display 3 |
    jq ".[] | select(.id == $YABAI_SPACE_ID and .\"native-fullscreen\" == 0).index" |
    xargs -I{} yabai -m space {} --layout float
EOF

yabai -m signal --add event=space_changed action="$action"


echo "yabai configuration loaded.."

